import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Link href={"/"}>profile</Link>
          <div></div>
          <Link href={"/file"}>route</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
